# Copyright 2015 - 2022, GIBIS-Unifesp and the WiRedPanda contributors
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build

on: [push, pull_request]

env:
  BUILD_TYPE: MinSizeRel

jobs:

# === Ubuntu ===
  Ubuntu-Qt5:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Install Qt5
      uses: jurplel/install-qt-action@v3
      with:
        version: 5.15.2
        modules: qtcharts
        
    - name: Install AppImage dependencies
      run: |
        sudo apt-get install libgstreamer-plugins-base1.0-0 libgstreamer-plugins-base1.0-dev 
        sudo apt-get install libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0-dev libxcb-render-util0 libxcb-xinerama0

    - name: Get linuxdeployqt
      run: |
        wget "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" -P ~/
        chmod +x ~/linuxdeployqt-continuous-x86_64.AppImage

    - name: Build
      run: |
        mkdir build
        cd build
        qmake ../WPanda.pro
        make -j2
        cd test
        xvfb-run ./WPanda-test
        
    - name: Make WiredPanda AppImage
      run: |
        PATH=/home/runner/work/wiredpanda-testing/Qt/5.15.2/gcc_64/bin:$PATH
        export PATH
        cp installer/Linux/portable_files/wpanda.desktop build/app/wpanda.desktop
        cp app/resources/wpanda.png build/app/wpanda.png
        ~/linuxdeployqt-continuous-x86_64.AppImage build/app/wpanda -appimage 

    - name: Upload WiredPanda AppImage
      uses: actions/upload-artifact@v3
      with:
        name: WiredPanda Linux (64-bit) AppImage
        path: WiRed_Panda*.AppImage

# === Windows ===
  Windows-Qt5:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Set up Git for properly handling symlinks on Windows
      run: git config --global core.symlinks true

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        arch: win64_mingw81
        version: 5.15.2
        modules: qtcharts

    - name: Build
      run: |
        mkdir build
        cd build
        qmake ../WPanda.pro
        make -j2
        make check
        
    - name: Deploy WiRedPanda binary
      run : |
        cp -r examples build\app\release
        cd build\app\release
        windeployqt --compiler-runtime wpanda.exe
        cp $env:Qt5_Dir\bin\libgcc_s_seh-1.dll .
        cp $env:Qt5_Dir\bin\libstdc++-6.dll .
        cp $env:Qt5_Dir\bin\libwinpthread-1.dll . 
        rm -r .\pch.h.gch\
        cd ..
        ren release wpanda
        
    - name: Upload WiRedPanda build
      continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: WiRedPanda Qt5 Windows (64-bit) build
        path: build\app\wpanda\

# === macOS ===
  macOS-Qt5:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Install
      run: brew install qt5 gdb

    - name: Build
      run: |
        QTDIR="/usr/local/opt/qt5/" && PATH="${QTDIR}/bin:$PATH" && LDFLAGS=-L${QTDIR}/lib && CPPFLAGS=-I${QTDIR}/include;
        mkdir build
        cd build
        qmake ../WPanda.pro
        make -j3
        make check
        
    - name: Deploy
      uses: actions/upload-artifact@v3
      with:
        name: 'WiRedPanda-Qt5-macOS'
        path: build/app/wpanda.app/Contents/MacOS/wpanda